apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1bly
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0019-tenant/tkrw-pr712-0075-0019-app/devfile-sample-1bly@sha256:0f2def62ebfce2b7e32af233ab8614d930a450d22112052f4cbb389fd08b9222
        name: my-nodejs
        resources: {}
status: {}
